version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:9000" # Map the host's port 8080 to the container's PHP-FPM port
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=invoice_creator_db
      - DB_USERNAME=invoice_creator_db_user
      - DB_PASSWORD=KMvyoUg4mH30lD3G9725t6AIIlwSFZ7m

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: invoice_creator_db
      POSTGRES_USER: invoice_creator_db_user
      POSTGRES_PASSWORD: KMvyoUg4mH30lD3G9725t6AIIlwSFZ7m
